packages:
  - "apps/*"
  - "packages/*"
  - "packages/cli/template"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.21
  vitest: npm:@voidzero-dev/vite-plus-test@latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  "@openrouter/sdk": true
  "@parcel/watcher": true
  core-js: true
  esbuild: true
  msw: true
  nx: true
  protobufjs: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - "@tanstack/ai-event-client@0.3.10"
  - "@tanstack/ai@0.21.3"
  - "@tanstack/ai-client@0.11.7"
  - "@tanstack/ai-react@0.11.7"
