import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, relative } from "node:path";

import type { ViteDevServer } from "vite";

import { writeIfChanged } from "./utils";

const HEADER = `/* ============================================================================
 * AUTO-GENERATED BY CAMOX — DO NOT EDIT
 *
 * This file is managed by the Camox Vite plugin and should stay gitignored.
 * Any manual edits will be automatically reverted by the dev server.
 * ============================================================================ */

/* eslint-disable */

// @ts-nocheck

`;

function generateCamoxLayout(
  authenticationUrl: string,
  apiUrl: string,
  projectSlug: string,
): string {
  return (
    HEADER +
    `import { Outlet, createFileRoute } from "@tanstack/react-router";
import { CamoxProvider } from "camox/CamoxProvider";
import { camoxApp } from "@/camox/app";

export const Route = createFileRoute("/_camox")({
  component: CamoxPathlessLayout,
});

function CamoxPathlessLayout() {
  return (
    <CamoxProvider camoxApp={camoxApp} authenticationUrl="${authenticationUrl}" apiUrl="${apiUrl}" projectSlug="${projectSlug}">
      <Outlet />
    </CamoxProvider>
  );
}
`
  );
}

function generatePageRoute(apiUrl: string): string {
  return (
    HEADER +
    `import { createFileRoute } from "@tanstack/react-router";
import {
  createMarkdownMiddleware,
  createPageLoader,
  createPageHead,
  PageRouteComponent,
} from "camox/_internal/pageRoute";
import { camoxApp } from "@/camox/app";

const markdownMiddleware = createMarkdownMiddleware("${apiUrl}");
const loader = createPageLoader("${apiUrl}");
const head = createPageHead(camoxApp);

export const Route = createFileRoute("/_camox/$")({
  server: {
    middleware: [markdownMiddleware],
  },
  component: PageRouteComponent,
  loader,
  head,
});
`
  );
}

function generateOgRoute(): string {
  return (
    HEADER +
    `import { createFileRoute } from "@tanstack/react-router";
import { createOgHandler } from "camox/_internal/ogRoute";
import { camoxApp } from "@/camox/app";

export const Route = createFileRoute("/_camox/og")({
  server: {
    handlers: createOgHandler(camoxApp),
  },
});
`
  );
}

function generateCmxRedirect(): string {
  return (
    HEADER +
    `import { createFileRoute, redirect } from "@tanstack/react-router";

export const Route = createFileRoute("/_camox/cmx")({
  component: RouteComponent,
  loader: () => {
    throw redirect({ to: "/cmx-studio" });
  },
});

function RouteComponent() {
  return null;
}
`
  );
}

function generateCmxStudio(): string {
  return (
    HEADER +
    `import { Outlet, createFileRoute } from "@tanstack/react-router";
import { CamoxStudio } from "camox/CamoxStudio";

export const Route = createFileRoute("/_camox/cmx-studio")({
  component: RouteComponent,
  notFoundComponent: () => <div>Studio page not found</div>,
});

function RouteComponent() {
  return (
    <CamoxStudio>
      <Outlet />
    </CamoxStudio>
  );
}
`
  );
}

function generateCmxStudioCatchAll(): string {
  return (
    HEADER +
    `import { Outlet, createFileRoute } from "@tanstack/react-router";
import { CamoxStudio } from "camox/CamoxStudio";

export const Route = createFileRoute("/_camox/cmx-studio/$")({
  component: RouteComponent,
  notFoundComponent: () => <div>Studio page not found</div>,
});

function RouteComponent() {
  return (
    <CamoxStudio>
      <Outlet />
    </CamoxStudio>
  );
}
`
  );
}

function generateCmxStudioContent(): string {
  return (
    HEADER +
    `import { createFileRoute } from "@tanstack/react-router";
import { CamoxContent } from "camox/CamoxContent";

export const Route = createFileRoute("/_camox/cmx-studio/content")({
  component: RouteComponent,
});

function RouteComponent() {
  return <CamoxContent />;
}
`
  );
}

type RouteFilesOptions = {
  routesDir: string;
  authenticationUrl: string;
  apiUrl: string;
  projectSlug: string;
};

function getRouteFileEntries({
  routesDir,
  authenticationUrl,
  apiUrl,
  projectSlug,
}: RouteFilesOptions) {
  const camoxDir = resolve(routesDir, "_camox");
  return [
    {
      path: resolve(routesDir, "_camox.tsx"),
      content: generateCamoxLayout(authenticationUrl, apiUrl, projectSlug),
    },
    { path: resolve(camoxDir, "$.tsx"), content: generatePageRoute(apiUrl) },
    { path: resolve(camoxDir, "og.tsx"), content: generateOgRoute() },
    { path: resolve(camoxDir, "cmx.tsx"), content: generateCmxRedirect() },
    { path: resolve(camoxDir, "cmx-studio.tsx"), content: generateCmxStudio() },
    { path: resolve(camoxDir, "cmx-studio.$.tsx"), content: generateCmxStudioCatchAll() },
    { path: resolve(camoxDir, "cmx-studio.content.tsx"), content: generateCmxStudioContent() },
  ];
}

export function generateRouteFiles(options: RouteFilesOptions) {
  const camoxDir = resolve(options.routesDir, "_camox");
  mkdirSync(camoxDir, { recursive: true });

  for (const entry of getRouteFileEntries(options)) {
    writeIfChanged(entry.path, entry.content);
  }
}

export function watchRouteFiles(options: RouteFilesOptions & { server: ViteDevServer }) {
  const { server, ...routeFilesOptions } = options;
  const entries = getRouteFileEntries(routeFilesOptions);
  const expectedByPath = new Map(entries.map((e) => [e.path, e.content]));

  server.watcher.on("change", (changedPath) => {
    const expected = expectedByPath.get(changedPath);
    if (!expected) return;

    const current = readFileSync(changedPath, "utf-8");
    if (current !== expected) {
      const rel = relative(server.config.root, changedPath);
      server.config.logger.warn(
        `Camox route file "${rel}" was modified — reverting to generated version.`,
        { timestamp: true },
      );
      writeFileSync(changedPath, expected, "utf-8");
    }
  });

  server.watcher.on("unlink", (deletedPath) => {
    const expected = expectedByPath.get(deletedPath);
    if (!expected) return;

    const rel = relative(server.config.root, deletedPath);
    server.config.logger.warn(`Camox route file "${rel}" was deleted — recreating.`, {
      timestamp: true,
    });
    writeFileSync(deletedPath, expected, "utf-8");
  });
}
