import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  lstatSync,
  symlinkSync,
  readlinkSync,
  writeFileSync,
} from "node:fs";
import { resolve, relative, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import type { ViteDevServer } from "vite";

import { writeIfChanged } from "./utils";

const HEADER = `<!-- AUTO-GENERATED BY CAMOX — DO NOT EDIT
This file is managed by the Camox Vite plugin.
Any manual edits will be automatically reverted by the dev server. -->

`;

const sdkRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");

type PackageManager = "pnpm" | "yarn" | "bun" | "npm";

const camoxCmdByPm: Record<PackageManager, string> = {
  pnpm: "pnpm camox",
  yarn: "yarn camox",
  bun: "bunx camox",
  npm: "npx camox",
};

function detectPackageManagerInDir(dir: string): PackageManager | undefined {
  const packageJsonPath = resolve(dir, "package.json");
  if (existsSync(packageJsonPath)) {
    try {
      const pkg = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
      const declared = typeof pkg.packageManager === "string" ? pkg.packageManager : "";
      const name = declared.split("@", 1)[0];
      if (name === "pnpm" || name === "yarn" || name === "bun" || name === "npm") return name;
    } catch {
      // fall through to lockfile detection
    }
  }

  if (existsSync(resolve(dir, "pnpm-lock.yaml"))) return "pnpm";
  if (existsSync(resolve(dir, "bun.lock")) || existsSync(resolve(dir, "bun.lockb"))) return "bun";
  if (existsSync(resolve(dir, "yarn.lock"))) return "yarn";
  if (existsSync(resolve(dir, "package-lock.json"))) return "npm";

  return undefined;
}

function detectPackageManager(appRoot: string): PackageManager {
  // Walk up from the app root toward the filesystem root. In monorepos the
  // lockfile / `packageManager` field typically lives at the workspace root,
  // not next to each app's package.json.
  let dir = resolve(appRoot);
  while (true) {
    const found = detectPackageManagerInDir(dir);
    if (found) return found;
    const parent = dirname(dir);
    if (parent === dir) return "npm";
    dir = parent;
  }
}

function getSkillNames(): string[] {
  const skillsDir = resolve(sdkRoot, "skills");
  return readdirSync(skillsDir).filter((name) => lstatSync(resolve(skillsDir, name)).isDirectory());
}

function generateSkillContent(skillName: string, appRoot: string): string {
  const skillPath = resolve(sdkRoot, `skills/${skillName}/SKILL.md`);
  const raw = readFileSync(skillPath, "utf-8");
  const pm = detectPackageManager(appRoot);
  const substituted = raw
    .replaceAll("{{PM_NAME}}", pm)
    .replaceAll("{{CAMOX_CMD}}", camoxCmdByPm[pm]);
  return HEADER + substituted;
}

function getSkillFileEntries(appRoot: string) {
  return getSkillNames().map((name) => ({
    path: resolve(appRoot, `.agents/skills/${name}/SKILL.md`),
    content: generateSkillContent(name, appRoot),
  }));
}

export function generateSkillFiles(appRoot: string) {
  for (const name of getSkillNames()) {
    mkdirSync(resolve(appRoot, `.agents/skills/${name}`), { recursive: true });
  }

  for (const entry of getSkillFileEntries(appRoot)) {
    writeIfChanged(entry.path, entry.content);
  }

  ensureClaudeSkillSymlinks(appRoot);
}

/**
 * For each skill directory in `.agents/skills/`, ensure a corresponding
 * symlink exists in `.claude/skills/` pointing to it via a relative path.
 */
function ensureClaudeSkillSymlinks(appRoot: string) {
  const agentsSkillsDir = resolve(appRoot, ".agents/skills");
  const claudeSkillsDir = resolve(appRoot, ".claude/skills");
  mkdirSync(claudeSkillsDir, { recursive: true });

  for (const name of readdirSync(agentsSkillsDir)) {
    const agentSkillPath = join(agentsSkillsDir, name);
    if (!lstatSync(agentSkillPath).isDirectory()) continue;

    const symlinkPath = join(claudeSkillsDir, name);
    const targetRelative = join("../../.agents/skills", name);

    try {
      const existing = readlinkSync(symlinkPath);
      if (existing === targetRelative) continue;
    } catch {
      // symlink doesn't exist or isn't a symlink — create it
    }

    symlinkSync(targetRelative, symlinkPath);
  }
}

export function watchSkillFiles(server: ViteDevServer, appRoot: string) {
  const entries = getSkillFileEntries(appRoot);
  const expectedByPath = new Map(entries.map((e) => [e.path, e.content]));

  server.watcher.on("change", (changedPath) => {
    const expected = expectedByPath.get(changedPath);
    if (!expected) return;

    const current = readFileSync(changedPath, "utf-8");
    if (current !== expected) {
      const rel = relative(server.config.root, changedPath);
      server.config.logger.warn(
        `Camox skill file "${rel}" was modified — reverting to generated version.`,
        { timestamp: true },
      );
      writeFileSync(changedPath, expected, "utf-8");
    }
  });

  server.watcher.on("unlink", (deletedPath) => {
    const expected = expectedByPath.get(deletedPath);
    if (!expected) return;

    const rel = relative(server.config.root, deletedPath);
    server.config.logger.warn(`Camox skill file "${rel}" was deleted — recreating.`, {
      timestamp: true,
    });
    writeFileSync(deletedPath, expected, "utf-8");
  });
}
